application: simple-gae-proxy
version: 1
runtime: python
api_version: 1

handlers:
- url: /google-dsapi-svc/.*
  script: redirections.py

- url: /solr/.*
  script: redirections.py

- url: /configs/
  static_dir: configs
  mime_type: application/json

- url: /
  static_dir: webapp
